-- =============================================================================
-- Lextr Semantic Layer — DDL (FIXED CONTRACT)
-- =============================================================================
-- Manifest version : 2.4.0+fable.1
-- Build            : regenerated by Claude Fable 5 (2026-06-14) — adds attribute pairing
-- Schema contract  : v2.4.0 — 5 schemas, 18 tables. Adds meta.attribute_pairing_catalog +
--                    meta.attribute_pairing_value_cache (attribute pairing). Pairing tables are
--                    ADDITIVE: if the V1 baseline is already applied, deliver them as a follow-on
--                    Flyway migration (e.g. V2__attribute_pairing.sql), NOT by editing V1.
--                    Schema DESIGN changes flow upstream, never made unilaterally.
-- Standards Document: STANDARDS-DOC <to confirm>            (P-09)
-- Tech stack       : PostgreSQL 16 · SQL-first · Flyway-owned · no JPA
-- Tenancy          : client_id (OPA-enforced isolation; Postgres RLS = future option)
-- Graph store      : Neo4j is the projection of relationship/lineage data;
--                    PostgreSQL is the system of record (this file).
-- Authorization    : externalized to OPA — NO policy logic in schema (no RLS day one)
-- Layer            : SHARED / COMMON. This schema is owned by Lextr Core and CONSUMED
--                    by all products (Lextr Core, Lextr Intelligence, Lextr EUC
--                    Remediation). A change here has cross-product blast radius and is
--                    governed more tightly: cross-product regression expected; a change
--                    must preserve every product's independent deployability.
-- Repo topology    : OPEN (monorepo vs multi-repo vs shared package — P-10). This file
--                    does not assume a layout; where it lands is a packaging decision.
-- =============================================================================
-- RING-FENCED CONTRACT. The build team builds AGAINST this schema and MUST NOT
-- alter it. Schema/standards are owned upstream (here) and flow downstream only.
-- Apply via Flyway as a versioned migration (e.g. V1__semantic_layer_baseline.sql).
-- =============================================================================
-- STANDARDS THIS DDL CONFORMS TO
--   Naming     : snake_case; schema.object.column; logical_short_nm <= 32 chars
--   Datatype   : canonical suffix vocabulary —
--                _cd CODE | _id IDENTIFIER | _amt AMOUNT | _rate RATE numeric(16,8)
--                _pct PERCENTAGE | _dt DATE | _ts TIMESTAMP | _flg/_ind BOOLEAN
--                _nbr NUMBER | _nm NAME | _txt free text
--   Must-have  : every table carries created_ts, created_by; mutable tables add
--                updated_ts, updated_by; governed tables add lifecycle_status_cd
--   Tenancy    : client_id varchar(40) present on tenant-scoped tables (nullable
--                = GLOBAL row); isolation enforced in OPA, not RLS (day one)
--   Taxonomy   : taxonomy_cd varchar(12); jurisdiction validation in OPA, not CHECK
-- Assumptions flagged inline as: -- [ASSUMED] ... (confirm against Standards Doc)
-- =============================================================================

-- ----------------------------------------------------------------------------
-- SCHEMAS  (Semantic Layer subset — all PostgreSQL)
-- ----------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS meta;          -- semantic catalog (system of record)
CREATE SCHEMA IF NOT EXISTS governance;    -- governance presets (DB-driven values)
CREATE SCHEMA IF NOT EXISTS ref;           -- reference / regulatory reference data
CREATE SCHEMA IF NOT EXISTS report;        -- regulatory report structure
CREATE SCHEMA IF NOT EXISTS wkfl;          -- approval workflow

-- ============================================================================
-- meta.schema_catalog — registered schemas
-- ============================================================================
DROP TABLE IF EXISTS meta.schema_catalog;
CREATE TABLE meta.schema_catalog (
    schema_cd            varchar(30)  PRIMARY KEY,
    schema_nm            varchar(100) NOT NULL,
    schema_purpose_txt   text,
    client_id            varchar(40),
    lifecycle_status_cd  varchar(30)  NOT NULL DEFAULT 'ACTIVE',
    created_ts           timestamptz  NOT NULL DEFAULT now(),
    created_by           varchar(100) NOT NULL DEFAULT current_user,
    updated_ts           timestamptz,
    updated_by           varchar(100),
    CONSTRAINT ck_sc_lifecycle CHECK (lifecycle_status_cd IN
        ('DRAFT','REVIEW','APPROVED','ACTIVE','DEPRECATED','RETIRED'))
);
CREATE INDEX ix_sc_client ON meta.schema_catalog (client_id);

-- ============================================================================
-- meta.data_connection — connection registry (per-object engine routing)
-- ============================================================================
DROP TABLE IF EXISTS meta.data_connection;
CREATE TABLE meta.data_connection (
    connection_id        uuid         PRIMARY KEY,
    connection_cd        varchar(50)  NOT NULL UNIQUE,
    connection_nm        varchar(100) NOT NULL,
    engine_cd            varchar(30)  NOT NULL,          -- POSTGRES | CLICKHOUSE | NEO4J
    connection_type_cd   varchar(30)  NOT NULL,
    source_mode_cd       varchar(30)  NOT NULL DEFAULT 'METADATA_PLUS_EXECUTION',
    host_nm              varchar(200),
    port_nbr             integer,
    database_nm          varchar(100),
    schema_nm_default    varchar(100),
    is_default_flg       boolean      NOT NULL DEFAULT false,
    is_active_flg        boolean      NOT NULL DEFAULT true,
    secrets_ref          varchar(200),                   -- Vault/KMS key reference only
    client_id            varchar(40),
    created_ts           timestamptz  NOT NULL DEFAULT now(),
    created_by           varchar(100) NOT NULL DEFAULT current_user,
    updated_ts           timestamptz,
    updated_by           varchar(100),
    CONSTRAINT ck_dc_engine CHECK (engine_cd IN ('POSTGRES','CLICKHOUSE','NEO4J'))
);
CREATE INDEX ix_dc_client ON meta.data_connection (client_id);

-- ============================================================================
-- meta.object_catalog — registered semantic objects
-- ============================================================================
DROP TABLE IF EXISTS meta.object_catalog;
CREATE TABLE meta.object_catalog (
    id                              bigserial    PRIMARY KEY,
    schema_cd                       varchar(30)  NOT NULL
        REFERENCES meta.schema_catalog (schema_cd),
    object_cd                       varchar(50)  NOT NULL,
    object_nm                       varchar(100) NOT NULL,
    object_type_cd                  varchar(50)  NOT NULL,
    object_desc                     text,
    object_purpose_txt              text,
    primary_business_process_txt    text,
    grain_txt                       text,
    source_system_cd                varchar(50),
    source_object_nm                varchar(100),
    refresh_frequency_cd            varchar(50),
    retention_policy_txt            text,
    partition_strategy_txt          text,
    row_count_approx                bigint,
    connection_id                   uuid REFERENCES meta.data_connection (connection_id),
    data_classification_cd          varchar(30),
    ai_governance_cd                varchar(50),
    pii_flg                         boolean      NOT NULL DEFAULT false,
    confidential_flg                boolean      NOT NULL DEFAULT false,
    semantic_layer_enabled_flg      boolean      NOT NULL DEFAULT false,
    ai_approved_flg                 boolean      NOT NULL DEFAULT false,
    lineage_enabled_flg             boolean      NOT NULL DEFAULT true,
    dependency_graph_enabled_flg    boolean      NOT NULL DEFAULT true,
    client_id                       varchar(40),                   -- NULL = GLOBAL
    lifecycle_status_cd             varchar(30)  NOT NULL DEFAULT 'DRAFT',
    governance_review_status_cd     varchar(30)  NOT NULL DEFAULT 'PENDING',
    standards_validation_status_cd  varchar(30)  NOT NULL DEFAULT 'PENDING',
    version_nbr                     integer      NOT NULL DEFAULT 1,
    created_ts                      timestamptz  NOT NULL DEFAULT now(),
    created_by                      varchar(100) NOT NULL DEFAULT current_user,
    updated_ts                      timestamptz,
    updated_by                      varchar(100),
    CONSTRAINT uq_object   UNIQUE (schema_cd, object_cd),
    CONSTRAINT ck_ob_type  CHECK (object_type_cd IN
        ('TABLE','VIEW','MATERIALIZED_VIEW','SEMANTIC_VIEW',
         'FUNCTION','PROCEDURE','SEQUENCE','EXTERNAL_TABLE')),
    CONSTRAINT ck_ob_data_class CHECK (data_classification_cd IN
        ('PUBLIC','INTERNAL','CONFIDENTIAL','RESTRICTED')),
    CONSTRAINT ck_ob_ai_gov CHECK (ai_governance_cd IN
        ('AI_ALLOWED','AI_RESTRICTED','AI_PROHIBITED',
         'SLM_ONLY','STRICT_AI_GOVERNANCE','POLICY_DRIVEN')),
    CONSTRAINT ck_ob_lifecycle CHECK (lifecycle_status_cd IN
        ('DRAFT','REVIEW','APPROVED','ACTIVE','DEPRECATED','RETIRED'))
);
CREATE INDEX ix_oc_schema   ON meta.object_catalog (schema_cd);
CREATE INDEX ix_oc_client   ON meta.object_catalog (client_id);
CREATE INDEX ix_oc_status   ON meta.object_catalog (lifecycle_status_cd);

-- ============================================================================
-- meta.attribute_catalog — attributes per object  (carries Taxonomy/MDRM)
-- ============================================================================
DROP TABLE IF EXISTS meta.attribute_catalog;
CREATE TABLE meta.attribute_catalog (
    id                          bigserial    PRIMARY KEY,
    client_id                   varchar(40)  NOT NULL,
    schema_cd                   varchar(30)  NOT NULL,
    object_cd                   varchar(50)  NOT NULL,
    attribute_cd                varchar(32)  NOT NULL,
    physical_attribute_nm       varchar(32)  NOT NULL,
    source_attribute_nm         varchar(100),
    logical_short_nm            varchar(32),                       -- <= 32 (standard)
    logical_long_nm             text,
    semantic_attribute_nm       text,
    attribute_desc              text,
    attribute_purpose_txt       text,
    canonical_data_type_cd      varchar(50)  NOT NULL,
    source_data_type_cd         varchar(50),
    postgresql_data_type_cd     varchar(50),
    clickhouse_data_type_cd     varchar(50),
    semantic_group_cd           varchar(50),
    ordinal_position            integer,
    nullable_flg                boolean      NOT NULL DEFAULT true,
    pk_flg                      boolean      NOT NULL DEFAULT false,
    fk_flg                      boolean      NOT NULL DEFAULT false,
    -- ---- Taxonomy / MDRM (first-class; jurisdiction validation in OPA) ----
    taxonomy_cd                 varchar(12),                       -- MDRM/Taxonomy
    taxonomy_source_cd          varchar(20),                       -- REG_DEFINED | LEXTR_ASSIGNED
    taxonomy_jurisdiction_cd    varchar(10),                       -- USA | non-USA ISO
    -- ----------------------------------------------------------------------
    dq_criticality_cd           varchar(30),
    regulatory_criticality_cd   varchar(30),
    regulatory_item_ref_txt     varchar(100),                      -- free-text citation
    pii_flg                     boolean      NOT NULL DEFAULT false,
    confidential_flg            boolean      NOT NULL DEFAULT false,
    masking_policy_cd           varchar(50),
    ai_business_context_txt     text,
    ai_prompt_guidance_txt      text,
    ai_relationship_context_txt text,
    ai_risk_audit_context_txt   text,
    ai_governance_context_txt   text,
    ai_example_txt              text,
    version_nbr                 integer      NOT NULL DEFAULT 1,
    created_ts                  timestamptz  NOT NULL DEFAULT now(),
    created_by                  varchar(100) NOT NULL DEFAULT current_user,
    updated_ts                  timestamptz,
    updated_by                  varchar(100),
    CONSTRAINT uq_attribute UNIQUE (schema_cd, object_cd, attribute_cd),
    CONSTRAINT fk_attr_object FOREIGN KEY (schema_cd, object_cd)
        REFERENCES meta.object_catalog (schema_cd, object_cd) ON DELETE CASCADE,
    CONSTRAINT ck_attr_tax_source CHECK (taxonomy_source_cd IS NULL OR taxonomy_source_cd IN
        ('REG_DEFINED','LEXTR_ASSIGNED'))
    -- [ASSUMED] taxonomy_cd length rule (USA reg=8, Lextr=8, non-USA=12) is enforced
    --           in OPA at registration, NOT as a DB CHECK, because the rule is
    --           jurisdictional/business policy and policy is externalized. Confirm.
);
CREATE INDEX ix_ac_client   ON meta.attribute_catalog (client_id);
CREATE INDEX ix_ac_object   ON meta.attribute_catalog (schema_cd, object_cd);
CREATE INDEX ix_ac_taxonomy ON meta.attribute_catalog (taxonomy_cd);

-- ============================================================================
-- meta.semantic_relationship_catalog — governed joins (PG system of record;
--    projected into Neo4j for traversal/visualization)
-- ============================================================================
DROP TABLE IF EXISTS meta.semantic_relationship_catalog;
CREATE TABLE meta.semantic_relationship_catalog (
    id                      bigserial    PRIMARY KEY,
    relationship_cd         varchar(100) NOT NULL UNIQUE,
    parent_schema_cd        varchar(30)  NOT NULL,
    parent_object_cd        varchar(50)  NOT NULL,
    parent_attribute_cd     varchar(32)  NOT NULL,
    child_schema_cd         varchar(30)  NOT NULL,
    child_object_cd         varchar(50)  NOT NULL,
    child_attribute_cd      varchar(32)  NOT NULL,
    relationship_type_cd    varchar(30)  NOT NULL,
    cardinality_cd          varchar(20)  NOT NULL,
    join_type_cd            varchar(20)  NOT NULL DEFAULT 'INNER',
    is_enforced_flg         boolean      NOT NULL DEFAULT false,
    is_nullable_flg         boolean      NOT NULL DEFAULT false,
    is_cross_engine_flg     boolean      NOT NULL DEFAULT false,
    relationship_desc       text,
    ai_join_guidance_txt    text,
    neo4j_synced_ts         timestamptz,                       -- last projection to Neo4j
    lifecycle_status_cd     varchar(30)  NOT NULL DEFAULT 'ACTIVE',
    created_ts              timestamptz  NOT NULL DEFAULT now(),
    created_by              varchar(100) NOT NULL DEFAULT current_user,
    updated_ts              timestamptz,
    updated_by              varchar(100),
    CONSTRAINT ck_rel_card CHECK (cardinality_cd IN
        ('ONE_TO_ONE','ONE_TO_MANY','MANY_TO_ONE','MANY_TO_MANY'))
);
CREATE INDEX ix_rel_parent ON meta.semantic_relationship_catalog (parent_schema_cd, parent_object_cd);
CREATE INDEX ix_rel_child  ON meta.semantic_relationship_catalog (child_schema_cd, child_object_cd);

-- ============================================================================
-- meta.attribute_logical_name_override — governed per-attribute rename
-- ============================================================================
DROP TABLE IF EXISTS meta.attribute_logical_name_override;
CREATE TABLE meta.attribute_logical_name_override (
    id                   bigserial    PRIMARY KEY,
    schema_cd            varchar(30)  NOT NULL,
    object_cd            varchar(50)  NOT NULL,
    attribute_cd         varchar(32)  NOT NULL,
    override_nm          varchar(32)  NOT NULL,                  -- <= 32
    override_reason_txt  text,
    override_status_cd   varchar(30)  NOT NULL DEFAULT 'PENDING',
    workflow_task_id     bigint,
    requested_by         varchar(100) NOT NULL DEFAULT current_user,
    requested_ts         timestamptz  NOT NULL DEFAULT now(),
    approved_by          varchar(100),
    approved_ts          timestamptz,
    CONSTRAINT ck_lno_status CHECK (override_status_cd IN ('PENDING','APPROVED','REJECTED')),
    CONSTRAINT fk_lno_attr FOREIGN KEY (schema_cd, object_cd, attribute_cd)
        REFERENCES meta.attribute_catalog (schema_cd, object_cd, attribute_cd) ON DELETE CASCADE
);

-- ============================================================================
-- meta.attribute_pairing_catalog — display→filter attribute substitution
--   A consumer filters on a human-readable DISPLAY attribute (e.g. customer_nm);
--   the Lextr-native semantic-service substitutes an indexed FILTER attribute
--   (e.g. customer_id) before SQL generation. Pairing is CROSS-ATTRIBUTE (two
--   distinct physical columns) — NOT logical→physical aliasing (same column).
--   Resolution is performed by the semantic-service (NO Cube.dev). Cross-engine
--   pairing is blocked by OPA POL-CE-002. A pairing may be ACTIVE only after its
--   filter attribute is confirmed indexed (activation gate, enforced in service).
-- ============================================================================
DROP TABLE IF EXISTS meta.attribute_pairing_catalog;
CREATE TABLE meta.attribute_pairing_catalog (
    id                              bigserial    PRIMARY KEY,
    pairing_cd                      varchar(80)  NOT NULL UNIQUE,
    pairing_nm                      varchar(200) NOT NULL,
    schema_cd                       varchar(30)  NOT NULL,
    object_cd                       varchar(50)  NOT NULL,
    display_attribute_cd            varchar(32)  NOT NULL,        -- what the user sees/filters on
    filter_attribute_cd             varchar(32)  NOT NULL,        -- what SQL actually uses (indexed)
    pairing_type_cd                 varchar(30)  NOT NULL DEFAULT 'LABEL_TO_KEY',
    lookup_strategy_cd              varchar(30)  NOT NULL DEFAULT 'CACHED_LOOKUP',
    lookup_inline_map_jsonb         jsonb,                        -- INLINE_MAP: {display:filter}
    lookup_sql_template_txt         text,                         -- RUNTIME_QUERY template
    lookup_cache_enabled_flg        boolean      NOT NULL DEFAULT true,
    lookup_cache_ttl_seconds_nbr    integer      NOT NULL DEFAULT 3600,
    cardinality_cd                  varchar(20)  NOT NULL DEFAULT 'ONE_TO_ONE',
    is_bidirectional_flg            boolean      NOT NULL DEFAULT false,
    is_cross_engine_flg             boolean      NOT NULL DEFAULT false,  -- POL-CE-002 gate
    filter_attribute_indexed_flg    boolean      NOT NULL DEFAULT true,   -- activation gate
    filter_attribute_index_type_cd  varchar(20),
    performance_gain_pct_est_nbr    integer,
    ai_context_txt                  text,
    client_id                       varchar(40),                  -- NULL = GLOBAL
    lifecycle_status_cd             varchar(30)  NOT NULL DEFAULT 'DRAFT',
    governance_review_status_cd     varchar(30)  NOT NULL DEFAULT 'PENDING',
    version_nbr                     integer      NOT NULL DEFAULT 1,
    created_ts                      timestamptz  NOT NULL DEFAULT now(),
    created_by                      varchar(100) NOT NULL DEFAULT current_user,
    updated_ts                      timestamptz,
    updated_by                      varchar(100),
    CONSTRAINT uq_apc_object_pair UNIQUE (schema_cd, object_cd,
                                          display_attribute_cd, filter_attribute_cd),
    CONSTRAINT fk_apc_object FOREIGN KEY (schema_cd, object_cd)
        REFERENCES meta.object_catalog (schema_cd, object_cd),
    CONSTRAINT ck_apc_type CHECK (pairing_type_cd IN
        ('LABEL_TO_KEY','NAME_TO_CODE','DESCRIPTION_TO_ID','DISPLAY_TO_FILTER')),
    CONSTRAINT ck_apc_strategy CHECK (lookup_strategy_cd IN
        ('CACHED_LOOKUP','INLINE_MAP','RUNTIME_QUERY')),
    CONSTRAINT ck_apc_cardinality CHECK (cardinality_cd IN
        ('ONE_TO_ONE','MANY_TO_ONE','ONE_TO_MANY')),
    CONSTRAINT ck_apc_diff_attrs CHECK (display_attribute_cd <> filter_attribute_cd),
    CONSTRAINT ck_apc_lifecycle CHECK (lifecycle_status_cd IN
        ('DRAFT','REVIEW','APPROVED','ACTIVE','DEPRECATED','RETIRED'))
    -- [ASSUMED-6] The "filter attribute must be indexed" activation gate is enforced in the
    --             service layer (checks pg_indexes), NOT as a DB constraint, consistent with
    --             logic-in-service. Confirm with Standards Doc (P-12).
);
CREATE INDEX ix_apc_object  ON meta.attribute_pairing_catalog (schema_cd, object_cd);
CREATE INDEX ix_apc_display ON meta.attribute_pairing_catalog (display_attribute_cd);
CREATE INDEX ix_apc_client  ON meta.attribute_pairing_catalog (client_id);

-- ============================================================================
-- meta.attribute_pairing_value_cache — resolved display→filter values (TTL)
--   Filled by the semantic-service on first resolution; read on cache hit.
--   Expiry (expires_ts) is evaluated in the service, not a generated column.
-- ============================================================================
DROP TABLE IF EXISTS meta.attribute_pairing_value_cache;
CREATE TABLE meta.attribute_pairing_value_cache (
    id                  bigserial    PRIMARY KEY,
    pairing_cd          varchar(80)  NOT NULL
        REFERENCES meta.attribute_pairing_catalog (pairing_cd) ON DELETE CASCADE,
    client_id           varchar(40)  NOT NULL DEFAULT 'GLOBAL',
    display_value_txt   varchar(500) NOT NULL,
    filter_value_txt    varchar(500) NOT NULL,    -- ONE_TO_MANY: JSON array -> SQL IN (...)
    is_one_to_many_flg  boolean      NOT NULL DEFAULT false,
    hit_count_nbr       bigint       NOT NULL DEFAULT 0,
    last_hit_ts         timestamptz,
    cached_ts           timestamptz  NOT NULL DEFAULT now(),
    expires_ts          timestamptz,
    CONSTRAINT uq_apvc UNIQUE (pairing_cd, display_value_txt, client_id)
);
CREATE INDEX ix_apvc_lookup ON meta.attribute_pairing_value_cache
    (pairing_cd, client_id, display_value_txt);

-- ============================================================================
-- meta.semantic_filter_lookup — reusable governed value sets (two-phase semi-join)
-- ============================================================================
DROP TABLE IF EXISTS meta.semantic_filter_lookup;
CREATE TABLE meta.semantic_filter_lookup (
    id                          bigserial    PRIMARY KEY,
    lookup_cd                   varchar(60)  NOT NULL UNIQUE,
    construction_type_cd        varchar(20)  NOT NULL,             -- SQL_QUERY | MANUAL_LIST
    manual_subtype_cd           varchar(30),                       -- ATTRIBUTE_VALIDATED | HAND_TYPED
    filter_obj                  varchar(120),
    filter_condition_txt        text,
    filter_attr_cd              varchar(32),
    validation_obj              varchar(120),
    validation_attr_cd          varchar(32),
    suggested_target_attr_cd    varchar(32),
    execution_strategy_cd       varchar(20)  NOT NULL DEFAULT 'IN_LIST',
    max_input_set_size          integer      NOT NULL DEFAULT 500,
    max_output_rows             integer      NOT NULL DEFAULT 10000,
    cache_ttl_min               integer      NOT NULL DEFAULT 60,
    review_period_days_override integer,
    rules_eligible_flg          boolean      NOT NULL DEFAULT true,
    qs_eligible_flg             boolean      NOT NULL DEFAULT true,
    ai_eligible_flg             boolean      NOT NULL DEFAULT false,
    replicate_to_ch_flg         boolean      NOT NULL DEFAULT false,
    description_txt             text,
    client_id                   varchar(40),                       -- NULL = GLOBAL
    governance_status_cd        varchar(30)  NOT NULL DEFAULT 'DRAFT',
    health_status_cd            varchar(30)  NOT NULL DEFAULT 'PENDING',
    last_certified_ts           timestamptz,
    last_certified_by           varchar(100),
    next_review_due_dt          date,
    lifecycle_status_cd         varchar(30)  NOT NULL DEFAULT 'ACTIVE',
    created_ts                  timestamptz  NOT NULL DEFAULT now(),
    created_by                  varchar(100) NOT NULL DEFAULT current_user,
    updated_ts                  timestamptz,
    updated_by                  varchar(100),
    CONSTRAINT ck_fl_ctype  CHECK (construction_type_cd IN ('SQL_QUERY','MANUAL_LIST')),
    CONSTRAINT ck_fl_sub    CHECK (manual_subtype_cd IS NULL OR manual_subtype_cd IN
        ('ATTRIBUTE_VALIDATED','HAND_TYPED')),
    CONSTRAINT ck_fl_strat  CHECK (execution_strategy_cd IN
        ('IN_LIST','BLOOM_FILTER','BRIDGE_TABLE')),
    CONSTRAINT ck_fl_gov    CHECK (governance_status_cd IN ('DRAFT','REVIEW','ACTIVE','SUSPENDED'))
);
CREATE INDEX ix_fl_client ON meta.semantic_filter_lookup (client_id);
CREATE INDEX ix_fl_health ON meta.semantic_filter_lookup (health_status_cd);

-- ============================================================================
-- meta.filter_lookup_value — manual-list values with lifecycle
-- ============================================================================
DROP TABLE IF EXISTS meta.filter_lookup_value;
CREATE TABLE meta.filter_lookup_value (
    id                      bigserial    PRIMARY KEY,
    lookup_cd               varchar(60)  NOT NULL
        REFERENCES meta.semantic_filter_lookup (lookup_cd) ON DELETE CASCADE,
    value_cd                varchar(100) NOT NULL,
    value_desc              text,
    lifecycle_status_cd     varchar(30)  NOT NULL DEFAULT 'ACTIVE',
    validated_flg           boolean      NOT NULL DEFAULT false,
    anticipated_dt          date,
    workflow_ref            varchar(60),
    last_seen_in_source_ts  timestamptz,
    auto_expire_after_days  integer,
    alert_txt               text,
    added_by                varchar(100) NOT NULL DEFAULT current_user,
    added_ts                timestamptz  NOT NULL DEFAULT now(),
    certified_by            varchar(100),
    certified_ts            timestamptz,
    retire_reason_txt       text,
    updated_ts              timestamptz,
    CONSTRAINT uq_flv UNIQUE (lookup_cd, value_cd),
    CONSTRAINT ck_flv_life CHECK (lifecycle_status_cd IN
        ('ACTIVE','INACTIVE_IN_SOURCE','ANTICIPATED','FUTURE_PENDING','RETIRED'))
);
CREATE INDEX ix_flv_lookup ON meta.filter_lookup_value (lookup_cd, lifecycle_status_cd);

-- ============================================================================
-- meta.filter_lookup_exec_log — Phase-1 execution audit
-- ============================================================================
DROP TABLE IF EXISTS meta.filter_lookup_exec_log;
CREATE TABLE meta.filter_lookup_exec_log (
    id                       bigserial    PRIMARY KEY,
    lookup_cd                varchar(60)  NOT NULL,
    executed_by              varchar(100) NOT NULL DEFAULT current_user,
    executed_ts              timestamptz  NOT NULL DEFAULT now(),
    phase1_duration_ms       integer,
    phase1_row_count         integer,
    phase1_cache_hit_flg     boolean      NOT NULL DEFAULT false,
    execution_strategy_used_cd varchar(20),
    phase2_duration_ms       integer,
    result_status_cd         varchar(20)  NOT NULL DEFAULT 'SUCCESS',
    error_txt                text,
    blocked_by_policy_cd     varchar(20),
    CONSTRAINT ck_flxl_status CHECK (result_status_cd IN ('SUCCESS','ERROR','BLOCKED'))
);
CREATE INDEX ix_flxl_lookup ON meta.filter_lookup_exec_log (lookup_cd, executed_ts DESC);

-- ============================================================================
-- meta.filter_lookup_binding — where each lookup is applied
-- ============================================================================
DROP TABLE IF EXISTS meta.filter_lookup_binding;
CREATE TABLE meta.filter_lookup_binding (
    id                       bigserial    PRIMARY KEY,
    lookup_cd                varchar(60)  NOT NULL
        REFERENCES meta.semantic_filter_lookup (lookup_cd) ON DELETE CASCADE,
    bound_obj                varchar(120) NOT NULL,
    bound_attr_cd            varchar(32)  NOT NULL,
    binding_context_cd       varchar(20)  NOT NULL,             -- RULE|QUERY_STUDIO|PIPELINE|LEXIE
    binding_ref              varchar(100),
    bound_by                 varchar(100) NOT NULL DEFAULT current_user,
    bound_ts                 timestamptz  NOT NULL DEFAULT now(),
    is_active_flg            boolean      NOT NULL DEFAULT true,
    deactivated_ts           timestamptz,
    deactivation_reason_txt  text,
    CONSTRAINT ck_flb_ctx CHECK (binding_context_cd IN
        ('RULE','QUERY_STUDIO','PIPELINE','LEXIE'))
);
CREATE INDEX ix_flb_lookup ON meta.filter_lookup_binding (lookup_cd);

-- ============================================================================
-- governance.policy_preset — DB-driven governance values (NEVER hardcoded)
-- ============================================================================
DROP TABLE IF EXISTS governance.policy_preset;
CREATE TABLE governance.policy_preset (
    policy_cd                       varchar(30)  PRIMARY KEY,
    policy_nm                       varchar(120) NOT NULL,
    policy_scope_cd                 varchar(40)  NOT NULL,
    default_value_txt               varchar(100) NOT NULL,
    data_type_cd                    varchar(20)  NOT NULL,       -- INTEGER|BOOLEAN|DECIMAL|STRING
    is_overrideable_flg             boolean      NOT NULL DEFAULT false,
    override_requires_approval_flg  boolean      NOT NULL DEFAULT true,
    effective_from_dt               date         NOT NULL DEFAULT CURRENT_DATE,
    effective_to_dt                 date,
    approved_by                     varchar(100),
    approved_ts                     timestamptz,
    created_ts                      timestamptz  NOT NULL DEFAULT now(),
    created_by                      varchar(100) NOT NULL DEFAULT current_user,
    CONSTRAINT ck_pp_dtype CHECK (data_type_cd IN ('INTEGER','BOOLEAN','DECIMAL','STRING'))
);

-- ============================================================================
-- wkfl.workflow_task — governance approval queue
-- ============================================================================
DROP TABLE IF EXISTS wkfl.workflow_task;
CREATE TABLE wkfl.workflow_task (
    id                  bigserial    PRIMARY KEY,
    task_type_cd        varchar(40)  NOT NULL,
    entity_type_cd      varchar(40)  NOT NULL,
    entity_ref          varchar(120) NOT NULL,
    task_status_cd      varchar(20)  NOT NULL DEFAULT 'PENDING',
    submitted_by        varchar(100) NOT NULL DEFAULT current_user,
    submitted_ts        timestamptz  NOT NULL DEFAULT now(),
    assigned_to         varchar(100),
    due_dt              date,
    description_txt     text,
    client_id           varchar(40),
    approved_by         varchar(100),
    approved_ts         timestamptz,
    approval_note_txt   text,
    CONSTRAINT ck_wt_status CHECK (task_status_cd IN
        ('PENDING','APPROVED','REJECTED','CANCELLED'))
);
CREATE INDEX ix_wt_status ON wkfl.workflow_task (task_status_cd, task_type_cd);

-- ============================================================================
-- meta.metadata_change_history — audit trail
-- ============================================================================
DROP TABLE IF EXISTS meta.metadata_change_history;
CREATE TABLE meta.metadata_change_history (
    id                  bigserial    PRIMARY KEY,
    entity_type_cd      varchar(40)  NOT NULL,
    entity_ref          varchar(120) NOT NULL,
    change_type_cd      varchar(20)  NOT NULL,
    changed_by          varchar(100) NOT NULL DEFAULT current_user,
    changed_ts          timestamptz  NOT NULL DEFAULT now(),
    old_value_json      jsonb,
    new_value_json      jsonb,
    change_reason_txt   text
);
CREATE INDEX ix_mch_entity ON meta.metadata_change_history (entity_type_cd, changed_ts DESC);

-- ============================================================================
-- report.report_definition — regulatory report registry
-- ============================================================================
DROP TABLE IF EXISTS report.report_definition;
CREATE TABLE report.report_definition (
    id                      bigserial    PRIMARY KEY,
    report_cd               varchar(80)  NOT NULL UNIQUE,
    report_nm               varchar(200) NOT NULL,
    report_type_cd          varchar(40),
    regulatory_body_cd      varchar(40),
    jurisdiction_cd         varchar(10),                       -- USA | non-USA ISO
    submission_frequency_cd varchar(30),
    ai_approved_flg         boolean      NOT NULL DEFAULT false,
    governance_status_cd    varchar(30)  NOT NULL DEFAULT 'DRAFT',
    effective_from_dt       date,
    lifecycle_status_cd     varchar(30)  NOT NULL DEFAULT 'ACTIVE',
    created_ts              timestamptz  NOT NULL DEFAULT now(),
    created_by              varchar(100) NOT NULL DEFAULT current_user,
    updated_ts              timestamptz,
    updated_by              varchar(100)
);

-- ============================================================================
-- report.report_line_definition — line-level model (carries Taxonomy/MDRM)
-- ============================================================================
DROP TABLE IF EXISTS report.report_line_definition;
CREATE TABLE report.report_line_definition (
    id                          bigserial    PRIMARY KEY,
    report_cd                   varchar(80)  NOT NULL
        REFERENCES report.report_definition (report_cd) ON DELETE CASCADE,
    line_cd                     varchar(50)  NOT NULL,
    line_nm                     varchar(200) NOT NULL,
    line_type_cd                varchar(30)  NOT NULL,
    schedule_cd                 varchar(50),
    series_cd                   varchar(50),
    line_desc                   text,
    source_schema_cd            varchar(30),
    source_object_cd            varchar(50),
    source_attribute_cd         varchar(32),
    calculation_rule_cd         varchar(80),
    aggregation_type_cd         varchar(30),
    sign_convention_cd          varchar(10)  NOT NULL DEFAULT 'POSITIVE',
    -- ---- Taxonomy / MDRM at the report-line level ----
    taxonomy_cd                 varchar(12),
    taxonomy_source_cd          varchar(20),
    taxonomy_jurisdiction_cd    varchar(10),
    -- --------------------------------------------------
    regulatory_item_ref_txt     varchar(100),
    is_mandatory_flg            boolean      NOT NULL DEFAULT false,
    parent_line_cd              varchar(50),
    level_nbr                   integer,
    created_ts                  timestamptz  NOT NULL DEFAULT now(),
    created_by                  varchar(100) NOT NULL DEFAULT current_user,
    updated_ts                  timestamptz,
    updated_by                  varchar(100),
    CONSTRAINT uq_rld UNIQUE (report_cd, line_cd),
    CONSTRAINT ck_rld_tax_source CHECK (taxonomy_source_cd IS NULL OR taxonomy_source_cd IN
        ('REG_DEFINED','LEXTR_ASSIGNED'))
);
CREATE INDEX ix_rld_report   ON report.report_line_definition (report_cd);
CREATE INDEX ix_rld_taxonomy ON report.report_line_definition (taxonomy_cd);

-- ============================================================================
-- ref.country — jurisdiction reference (drives taxonomy jurisdiction validation)
-- ============================================================================
DROP TABLE IF EXISTS ref.country;
CREATE TABLE ref.country (
    country_cd                  varchar(3)   PRIMARY KEY,        -- ISO 3166-1 alpha-3
    country_nm                  varchar(100) NOT NULL,
    iso2_cd                     varchar(2),
    is_usa_flg                  boolean      NOT NULL DEFAULT false,
    is_regulatory_jurisdiction_flg boolean   NOT NULL DEFAULT false,
    created_ts                  timestamptz  NOT NULL DEFAULT now(),
    created_by                  varchar(100) NOT NULL DEFAULT current_user
);

-- ============================================================================
-- SEED — governance presets (GOV-FL-001..006). Values DB-driven; never hardcoded.
-- ============================================================================
INSERT INTO governance.policy_preset
  (policy_cd, policy_nm, policy_scope_cd, default_value_txt, data_type_cd,
   is_overrideable_flg, override_requires_approval_flg) VALUES
 ('GOV-FL-001','Minimum review frequency (floor, days)','FILTER_LOOKUP','90','INTEGER',true,true),
 ('GOV-FL-002','Auto-expire window (days)','FILTER_LOOKUP','180','INTEGER',true,true),
 ('GOV-FL-003','Grace period (days)','FILTER_LOOKUP','14','INTEGER',true,true),
 ('GOV-FL-004','Anticipated values require approval','FILTER_LOOKUP','true','BOOLEAN',false,false),
 ('GOV-FL-005','Maximum values per lookup','FILTER_LOOKUP','500','INTEGER',true,true),
 ('GOV-FL-006','HAND_TYPED review factor','FILTER_LOOKUP','0.5','DECIMAL',false,false)
ON CONFLICT (policy_cd) DO NOTHING;

-- ============================================================================
-- SEED — connection registry (PostgreSQL primary, ClickHouse analytics, Neo4j graph)
-- ============================================================================
INSERT INTO meta.data_connection
  (connection_id, connection_cd, connection_nm, engine_cd, connection_type_cd, is_default_flg, client_id) VALUES
 ('00000000-0000-0000-0000-000000000001','LEXTR_PG','Lextr PostgreSQL','POSTGRES','PRIMARY',true,'GLOBAL'),
 ('00000000-0000-0000-0000-000000000002','LEXTR_CH','Lextr ClickHouse','CLICKHOUSE','ANALYTICS',false,'GLOBAL'),
 ('00000000-0000-0000-0000-000000000003','LEXTR_NEO4J','Lextr Neo4j Graph','NEO4J','GRAPH',false,'GLOBAL')
ON CONFLICT (connection_id) DO NOTHING;

-- =============================================================================
-- ASSUMPTIONS / CONVENTIONS FLAGGED FOR CONFIRMATION (downstream-owned upstream)
--   [ASSUMED-1] taxonomy_cd jurisdiction length rule (USA=8, Lextr=8, non-USA=12)
--               enforced in OPA at registration, not as a DB CHECK. Confirm.
--   [ASSUMED-2] client_id varchar(40) length. Standards Doc to confirm exact length.
--   [ASSUMED-3] No Postgres RLS day one (per stack doc); isolation in OPA. RLS is a
--               documented future option, not in this baseline.
--   [ASSUMED-4] Neo4j holds the projected graph; PG is system of record. The
--               relationship/lineage projection job direction is PG -> Neo4j.
--   [ASSUMED-5] effective review period / health are computed in the service layer
--               (Java) reading governance.policy_preset — NOT as PG functions/triggers
--               — because the stack is SQL-first + no-JPA with logic in services.
--               (Prototype used PG functions; standard stack moves this to service.)
-- =============================================================================
